### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by mark-wiemer** [stirante/minecraft-item-db#1]
Thanks for this awesome DB! But it'd be much easier to verify and improve if the source code for getting this data were here. Do you have any plans to add this to the repo?

**Comment by stirante** [comment]
I intentionally left out source code, because:
1. I used content generated from developer version of Minecraft
2. I also did a lot of reverse engineering to get a lot of those values automatically
3. Overall code is very messy
4. I had to manually create a tonne of very specific fixes

Due to those reasons, it's not something anyone could run as well as it might leak information I'm not allowed to share (debug and unreleased items had to be specifically filtered out).

Overall my intent was to first create the initial DB and then gradually with each version add new items and blocks manually or semi-manually, since that seems much easier than doing whole DB manually from scratch.

**Comment by mark-wiemer** [comment]
Makes sense, I'm closing this as not planned :)
